In this stage I brushed up my python🐍 skills🛠️, and learned some new stuff to get started with machine learning.

In [1]:
string = "dfjndfjn"
string[::-1]

'njfdnjfd'

In [2]:
len(string)

8

## Working with Numpy library

### NumPy is often significantly faster than standard Python code for numerical computations due to several reasons:

1. **Vectorization**
Avoiding Loops: NumPy allows you to perform operations on entire arrays without the need for explicit loops in Python. This process, called vectorization, leverages efficient, low-level implementations in C and avoids the overhead of Python loops.
Batch Operations: Operations on entire arrays are executed in a single batch, which reduces the overhead of repeatedly interpreting Python code.
2. **Optimized C and Fortran Libraries**
Core Implementation: NumPy's core operations are implemented in C and Fortran, which are compiled languages known for their high performance. These languages can execute operations more efficiently than Python.
BLAS and LAPACK: NumPy can link to highly optimized libraries like BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package) for many of its operations, particularly those involving linear algebra. These libraries are optimized for performance on various hardware architectures.
3. **Efficient Memory Management**
Contiguous Memory Layout: NumPy arrays are stored in contiguous blocks of memory, which improves cache performance and memory access patterns. This is in contrast to Python lists, which store elements as pointers to objects scattered in memory.
Data Types: NumPy allows you to specify data types explicitly, enabling more efficient use of memory and operations tailored to specific data types (e.g., 32-bit or 64-bit floats).

In [10]:
import numpy as np


In [11]:
# Comparing the time in below cases tell us how fast numpy can be!!
import time

# Create a large array
size = 10**6
array = np.random.rand(size)

# Sum using a Python loop
start_time = time.time()
total = sum(array)
python_time = time.time() - start_time
print(f"Python loop: {python_time:.10f} seconds")

# Sum using NumPy
start_time = time.time()
total = np.sum(array)
numpy_time = time.time() - start_time
print(f"NumPy: {numpy_time:.10f} seconds")


Python loop: 0.0466461182 seconds
NumPy: 0.0058786869 seconds


In [17]:
np1 = np.array([1, 2])
print(type(np1))
np1

<class 'numpy.ndarray'>


array([1, 2])

In [24]:
np1.shape

(2,)

In [19]:
# 2-D numpy array
Mat1 = np.array([[1, 2, 3], [10, 11, 12]])
Mat1

array([[ 1,  2,  3],
       [10, 11, 12]])

In [49]:
# updating element at row 1 and column 2
Mat1[1, 2] = 100

In [50]:
Mat1

array([[  1,   2,   3],
       [ 10,  11, 100]])

In [39]:
Mat1.shape

(2, 3)

In [40]:
Mat1.ndim

2

In [41]:
# Getting datatype 
Mat1.dtype

dtype('int32')

In [42]:
np2 = np.array([1, 2, 3.0])

In [43]:
np2.dtype

dtype('float64')

In [52]:
np3 = np.array([1, 2.34, "dfjbvdj"])

In [53]:
np3

array(['1', '2.34', 'dfjbvdj'], dtype='<U32')

In [54]:
np3[0] = "jgjrnfjg"

In [55]:
np3

array(['jgjrnfjg', '2.34', 'dfjbvdj'], dtype='<U32')

In [57]:
# arrange in numpy
Mat = np.arange(1, 11, 3)
Mat

array([ 1,  4,  7, 10])

In [61]:
# linspace in numpy, 10 quidistant elements
Mat = np.linspace(1, 11, 10)
Mat

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [68]:
# 5 X 5 matrix, with each element between 0 and 1, uniform distribution
Mat4 = np.random.rand(5, 5)

In [69]:
Mat4

array([[0.83895901, 0.36801453, 0.65853515, 0.9572761 , 0.18410706],
       [0.8902169 , 0.02624809, 0.69803157, 0.97979502, 0.87545162],
       [0.22305222, 0.98678818, 0.25316989, 0.01726981, 0.76510164],
       [0.78623042, 0.41848612, 0.91062087, 0.24936698, 0.97286439],
       [0.56777683, 0.94880363, 0.23241473, 0.64378712, 0.9777338 ]])

In [70]:
#  Normally distributed random numbers
Mat5 = np.random.randn(10, 10)
Mat5

array([[-1.14848052,  0.52052388, -0.49556301,  0.74553602, -1.52971073,
        -0.02738794, -0.1393623 , -0.04599663,  1.02186277, -0.83605153],
       [-2.19135243,  1.02302065, -0.66218821, -0.56026477, -0.17655636,
        -0.0352456 , -0.31231979, -1.09160987,  0.36903082,  1.19613789],
       [ 0.7625414 ,  1.68960589, -1.44350645,  0.43481957, -0.94411906,
         1.35024105, -0.40913146,  0.97916386, -0.3069756 ,  0.30223842],
       [ 0.5168657 ,  1.05691473, -0.13654635,  0.70788259, -0.01295608,
         0.94341736,  0.41695603, -0.19788293,  0.56850277, -1.65296359],
       [ 0.35417469,  0.51171929,  0.05261298, -0.43774875, -1.57453987,
         0.54618361, -0.68501068,  0.48069262, -0.43673711, -0.03905903],
       [ 0.55133477,  1.7906898 ,  0.44412162, -0.59236474, -0.55564305,
         1.19765464,  1.14316655,  0.30557906, -0.18779054, -0.57062831],
       [-1.19263634,  1.47027902,  1.85267816,  0.23836513, -0.49010637,
        -0.83335955,  1.63629624, -0.15359024

In [76]:
np.diag([10, 10, 11 , 12])

array([[10,  0,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0, 11,  0],
       [ 0,  0,  0, 12]])

In [84]:
np.zeros([2, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
np.ones([2, 2, 2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [89]:
# slicings 
Mat5 = np.random.randn(5, 6)
Mat5

array([[-1.37457789,  1.00700086, -0.60928945,  0.15471863, -1.93896376,
         0.19154672],
       [ 0.47864925,  0.11097679,  0.25629466, -1.36469044,  1.13400544,
         0.35626665],
       [ 0.19789176,  0.5265725 , -2.43991049,  0.90384109,  0.4412204 ,
         0.64764989],
       [ 0.37663714, -0.68532302,  0.14632429,  1.81321787,  0.80601039,
         0.3839172 ],
       [ 0.4621727 ,  0.97467569, -1.2333432 , -0.98308389, -0.17549267,
         0.5379203 ]])

In [90]:
Mat5[0, 0]

-1.374577894853716

In [92]:
# Rows with index 0, 1 and 2 and all columns
Mat5[0:3, :]

array([[-1.37457789,  1.00700086, -0.60928945,  0.15471863, -1.93896376,
         0.19154672],
       [ 0.47864925,  0.11097679,  0.25629466, -1.36469044,  1.13400544,
         0.35626665],
       [ 0.19789176,  0.5265725 , -2.43991049,  0.90384109,  0.4412204 ,
         0.64764989]])

In [93]:
type(Mat5.shape)

tuple